/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myApplication;

import objectFactory.User;
import businessLayer.BLUser;
import javax.swing.JOptionPane;
import businessLayer.BLServices;
import objectFactory.Rating;
import businessLayer.BLRating;
import objectFactory.Services;
import objectFactory.Request;
import objectFactory.Response;
import businessLayer.BLRequestResponse;

/**
 *
 * @author Kriss
 */
public class AdministratorDesktop extends javax.swing.JFrame {

    /**
     * Creates new form AdministratorDesktop
     */
    public AdministratorDesktop() {
        super("Administrator Desktop");
        initComponents();
        this.user = new User();
        this.services = new Services();
        
    }

    public void setUser(User usr) {
        this.user = usr;

    }

    public void setServices(Services services) {
        this.services = services;
    }

    public void setRating(Rating rating) {
        this.rating = rating;
    }

    public void setRequest(Request request) {
        this.request = request;
    }

    public void setResponse(Response response) {
        this.response = response;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jSeparator1 = new javax.swing.JSeparator();
        menuBar = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        menu_logOut = new javax.swing.JMenuItem();
        menu_exit = new javax.swing.JMenuItem();
        menu_view = new javax.swing.JMenu();
        menu_viewClientProfile = new javax.swing.JMenuItem();
        menu_viewOfficeStaffProfile = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menu_viewSubscription = new javax.swing.JMenuItem();
        menu_viewServiceList = new javax.swing.JMenuItem();
        menu_viewAccountData = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        menu_viewRequest = new javax.swing.JMenuItem();
        menu_viewResponse = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menu_viewPi_chart = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu_subscription = new javax.swing.JMenu();
        menu_newSubscription = new javax.swing.JMenuItem();
        menu_updateSubscription = new javax.swing.JMenuItem();
        menu_input_Data = new javax.swing.JMenu();
        menu_updateClientProfile = new javax.swing.JMenuItem();
        menu_deleteClientProfile = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menu_insertService = new javax.swing.JMenuItem();
        menu_updateService = new javax.swing.JMenuItem();
        menu_deleteService = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menu_payAccount = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menu_respond = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menu_createStaffProfile = new javax.swing.JMenuItem();
        menu_updateStaffProfile = new javax.swing.JMenuItem();
        menu_deleteStaffProfile = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 700));

        desktopPane.add(jSeparator1);
        jSeparator1.setBounds(260, 40, 0, 2);

        menu_file.setMnemonic('f');
        menu_file.setText("File");

        menu_logOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menu_logOut.setText("Log out");
        menu_logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_logOutActionPerformed(evt);
            }
        });
        menu_file.add(menu_logOut);

        menu_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menu_exit.setMnemonic('x');
        menu_exit.setText("Exit");
        menu_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_exitActionPerformed(evt);
            }
        });
        menu_file.add(menu_exit);

        menuBar.add(menu_file);

        menu_view.setText("View");

        menu_viewClientProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_viewClientProfile.setText("Client Profile");
        menu_viewClientProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_viewClientProfileActionPerformed(evt);
            }
        });
        menu_view.add(menu_viewClientProfile);

        menu_viewOfficeStaffProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        menu_viewOfficeStaffProfile.setText("Office Staff Profile");
        menu_viewOfficeStaffProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_viewOfficeStaffProfileActionPerformed(evt);
            }
        });
        menu_view.add(menu_viewOfficeStaffProfile);
        menu_view.add(jSeparator6);

        menu_viewSubscription.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menu_viewSubscription.setText("Subscription");
        menu_viewSubscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_viewSubscriptionActionPerformed(evt);
            }
        });
        menu_view.add(menu_viewSubscription);

        menu_viewServiceList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menu_viewServiceList.setText("Service List");
        menu_viewServiceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_viewServiceListActionPerformed(evt);
            }
        });
        menu_view.add(menu_viewServiceList);

        menu_viewAccountData.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        menu_viewAccountData.setText("Account Data");
        menu_viewAccountData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_viewAccountDataActionPerformed(evt);
            }
        });
        menu_view.add(menu_viewAccountData);
        menu_view.add(jSeparator7);

        menu_viewRequest.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        menu_viewRequest.setText("Current Request");
        menu_viewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_viewRequestActionPerformed(evt);
            }
        });
        menu_view.add(menu_viewRequest);

        menu_viewResponse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menu_viewResponse.setText("Request/Response");
        menu_viewResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_viewResponseActionPerformed(evt);
            }
        });
        menu_view.add(menu_viewResponse);
        menu_view.add(jSeparator8);

        menu_viewPi_chart.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menu_viewPi_chart.setText("Rating");
        menu_viewPi_chart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_viewPi_chartActionPerformed(evt);
            }
        });
        menu_view.add(menu_viewPi_chart);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Feedback");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_view.add(jMenuItem1);

        menuBar.add(menu_view);

        menu_subscription.setText("Subscription");

        menu_newSubscription.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menu_newSubscription.setText("New");
        menu_newSubscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_newSubscriptionActionPerformed(evt);
            }
        });
        menu_subscription.add(menu_newSubscription);

        menu_updateSubscription.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menu_updateSubscription.setText("Update");
        menu_updateSubscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_updateSubscriptionActionPerformed(evt);
            }
        });
        menu_subscription.add(menu_updateSubscription);

        menuBar.add(menu_subscription);

        menu_input_Data.setText("Data");

        menu_updateClientProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_updateClientProfile.setText("Update Client Profile");
        menu_updateClientProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_updateClientProfileActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_updateClientProfile);

        menu_deleteClientProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_deleteClientProfile.setText("Delete Client Profile");
        menu_deleteClientProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_deleteClientProfileActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_deleteClientProfile);
        menu_input_Data.add(jSeparator2);

        menu_insertService.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_insertService.setText("Insert Service");
        menu_insertService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_insertServiceActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_insertService);

        menu_updateService.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_updateService.setText("Update Service");
        menu_updateService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_updateServiceActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_updateService);

        menu_deleteService.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_deleteService.setText("Delete Service");
        menu_deleteService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_deleteServiceActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_deleteService);
        menu_input_Data.add(jSeparator3);

        menu_payAccount.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_payAccount.setText("Pay Account");
        menu_payAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_payAccountActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_payAccount);
        menu_input_Data.add(jSeparator4);

        menu_respond.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_respond.setText("Respond");
        menu_respond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_respondActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_respond);
        menu_input_Data.add(jSeparator5);

        menu_createStaffProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_createStaffProfile.setText("Create Staff Profile");
        menu_createStaffProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_createStaffProfileActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_createStaffProfile);

        menu_updateStaffProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_updateStaffProfile.setText("Update Staff Profile");
        menu_updateStaffProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_updateStaffProfileActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_updateStaffProfile);

        menu_deleteStaffProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_deleteStaffProfile.setText("Delete Staff Profile");
        menu_deleteStaffProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_deleteStaffProfileActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_deleteStaffProfile);

        menuBar.add(menu_input_Data);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_logOutActionPerformed
        // TODO add your handling code here:
        this.dispose();//setVisible(false);
        LoginForm1 lf = new LoginForm1();
        lf.setVisible(true);

    }//GEN-LAST:event_menu_logOutActionPerformed

    private void menu_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_exitActionPerformed

        int option = JOptionPane.showConfirmDialog(rootPane, "Do you really want to exit the program?", null, 2);
        if (option == JOptionPane.OK_OPTION) {
            System.exit(0);
        } else {
            JOptionPane.getRootFrame();//setVisible(false);
        }

    }//GEN-LAST:event_menu_exitActionPerformed

    private void menu_createStaffProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_createStaffProfileActionPerformed
        CreateStaffProfile csp = new CreateStaffProfile();
        desktopPane.add(csp);
        csp.setVisible(true);
    }//GEN-LAST:event_menu_createStaffProfileActionPerformed

    private void menu_viewClientProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_viewClientProfileActionPerformed
        // TODO add your handling code here:
        ViewClientProfile vpd = new ViewClientProfile();
        desktopPane.add(vpd);
        vpd.setUser(user);
        vpd.setVisible(true);
        vpd.viewClientProfile();

    }//GEN-LAST:event_menu_viewClientProfileActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ViewFeedback vf = new ViewFeedback();
        desktopPane.add(vf);
        vf.setFeedback(feedback);
        vf.setVisible(true);
        vf.viewFeedback();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menu_viewOfficeStaffProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_viewOfficeStaffProfileActionPerformed
        // TODO add your handling code here:
        ViewOfficeStaffProfile vosp = new ViewOfficeStaffProfile();
        desktopPane.add(vosp);
        vosp.setUser(user);
        vosp.setVisible(true);
        vosp.viewOfficeStaffProfile();

    }//GEN-LAST:event_menu_viewOfficeStaffProfileActionPerformed

    private void menu_viewServiceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_viewServiceListActionPerformed
        // TODO add your handling code here:
        ViewServiceList vsl = new ViewServiceList();
        desktopPane.add(vsl);
        vsl.setServices(services);
        vsl.setVisible(true);
        vsl.viewServiceList();

    }//GEN-LAST:event_menu_viewServiceListActionPerformed

    private void menu_viewSubscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_viewSubscriptionActionPerformed
        ViewSubscription vs = new ViewSubscription();
        desktopPane.add(vs);
        vs.setVisible(true);
        vs.viewEmptyServiceList();

    }//GEN-LAST:event_menu_viewSubscriptionActionPerformed

    private void menu_viewAccountDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_viewAccountDataActionPerformed
        ViewAccountData vad = new ViewAccountData();
        desktopPane.add(vad);
        vad.setVisible(true);
        vad.viewAccountData();

    }//GEN-LAST:event_menu_viewAccountDataActionPerformed

    private void menu_viewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_viewRequestActionPerformed
        ViewCurrentRequest vsl = new ViewCurrentRequest();
        desktopPane.add(vsl);
        vsl.setVisible(true);
        vsl.viewCurrentRequest();

    }//GEN-LAST:event_menu_viewRequestActionPerformed

    private void menu_viewResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_viewResponseActionPerformed
        ViewRequestResponse vres = new ViewRequestResponse();
        desktopPane.add(vres);
        vres.setRequest(request);
        vres.setResponse(response);
        vres.setVisible(true);
        vres.viewRequestResponse();

    }//GEN-LAST:event_menu_viewResponseActionPerformed

    private void menu_viewPi_chartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_viewPi_chartActionPerformed
        ViewRating vpc = new ViewRating();
        Rating rating = new Rating();
        vpc.setRating(rating);
        vpc.drawPi_chart();

    }//GEN-LAST:event_menu_viewPi_chartActionPerformed

    private void menu_newSubscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_newSubscriptionActionPerformed
        CreateClientProfile ccp = new CreateClientProfile();
        desktopPane.add(ccp);
        ccp.setVisible(true);
        ccp.viewServiceList();
    }//GEN-LAST:event_menu_newSubscriptionActionPerformed

    private void menu_updateSubscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_updateSubscriptionActionPerformed
        UpdateSubscription us_sl = new UpdateSubscription();
        desktopPane.add(us_sl);
        us_sl.setVisible(true);
        us_sl.viewEmptyServiceList();
    }//GEN-LAST:event_menu_updateSubscriptionActionPerformed

    private void menu_updateClientProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_updateClientProfileActionPerformed
        UpdateClientProfile up = new UpdateClientProfile();
        desktopPane.add(up);
        up.setVisible(true);
        up.updateClientProfile();
    }//GEN-LAST:event_menu_updateClientProfileActionPerformed

    private void menu_deleteClientProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_deleteClientProfileActionPerformed
        DeleteClientProfile dcp = new DeleteClientProfile();
        desktopPane.add(dcp);
        dcp.setVisible(true);
        dcp.deleteClientProfile();
    }//GEN-LAST:event_menu_deleteClientProfileActionPerformed

    private void menu_insertServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_insertServiceActionPerformed
        InsertService is = new InsertService();
        desktopPane.add(is);
        is.setVisible(true);
    }//GEN-LAST:event_menu_insertServiceActionPerformed

    private void menu_updateServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_updateServiceActionPerformed
        UpdateService us_l = new UpdateService();
        desktopPane.add(us_l);
        us_l.setServices(services);
        us_l.setVisible(true);
        us_l.updateService_List();
    }//GEN-LAST:event_menu_updateServiceActionPerformed

    private void menu_deleteServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_deleteServiceActionPerformed
        DeleteService ds = new DeleteService();
        desktopPane.add(ds);
        ds.setServices(services);
        ds.setVisible(true);
        ds.deleteService();
    }//GEN-LAST:event_menu_deleteServiceActionPerformed

    private void menu_payAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_payAccountActionPerformed
        PaySubscribedAccount pa = new PaySubscribedAccount();
        desktopPane.add(pa);
        pa.setVisible(true);
        pa.viewAccountData();

    }//GEN-LAST:event_menu_payAccountActionPerformed

    private void menu_respondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_respondActionPerformed
        Input_DataRespond rm = new Input_DataRespond();
        desktopPane.add(rm);
        rm.setVisible(true);
        rm.input_DataRespond();
    }//GEN-LAST:event_menu_respondActionPerformed

    private void menu_updateStaffProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_updateStaffProfileActionPerformed
        UpdateStaffProfile usp = new UpdateStaffProfile();
        desktopPane.add(usp);
        usp.setVisible(true);
        usp.updateOfficeStaffProfile();
    }//GEN-LAST:event_menu_updateStaffProfileActionPerformed

    private void menu_deleteStaffProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_deleteStaffProfileActionPerformed
        DeleteStaffProfile dsp = new DeleteStaffProfile();
        desktopPane.add(dsp);
        dsp.setVisible(true);
        dsp.deleteOfficeStaffProfile();
    }//GEN-LAST:event_menu_deleteStaffProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministratorDesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menu_createStaffProfile;
    private javax.swing.JMenuItem menu_deleteClientProfile;
    private javax.swing.JMenuItem menu_deleteService;
    private javax.swing.JMenuItem menu_deleteStaffProfile;
    private javax.swing.JMenuItem menu_exit;
    private javax.swing.JMenu menu_file;
    private javax.swing.JMenu menu_input_Data;
    private javax.swing.JMenuItem menu_insertService;
    private javax.swing.JMenuItem menu_logOut;
    private javax.swing.JMenuItem menu_newSubscription;
    private javax.swing.JMenuItem menu_payAccount;
    private javax.swing.JMenuItem menu_respond;
    private javax.swing.JMenu menu_subscription;
    private javax.swing.JMenuItem menu_updateClientProfile;
    private javax.swing.JMenuItem menu_updateService;
    private javax.swing.JMenuItem menu_updateStaffProfile;
    private javax.swing.JMenuItem menu_updateSubscription;
    private javax.swing.JMenu menu_view;
    private javax.swing.JMenuItem menu_viewAccountData;
    private javax.swing.JMenuItem menu_viewClientProfile;
    private javax.swing.JMenuItem menu_viewOfficeStaffProfile;
    private javax.swing.JMenuItem menu_viewPi_chart;
    private javax.swing.JMenuItem menu_viewRequest;
    private javax.swing.JMenuItem menu_viewResponse;
    private javax.swing.JMenuItem menu_viewServiceList;
    private javax.swing.JMenuItem menu_viewSubscription;
    // End of variables declaration//GEN-END:variables

    private objectFactory.User user;
    private businessLayer.BLUser bluser;

    private objectFactory.Feedback feedback;
    private businessLayer.BLFeedback blfeedback;

    private objectFactory.Services services;
    private businessLayer.BLServices blservices;

    private objectFactory.Request request;
    private objectFactory.Response response;

    private objectFactory.Rating rating;
    private businessLayer.BLRating blrating;
}
