/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myApplication;

import businessLayer.BLUser;
import java.sql.ResultSet;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objectFactory.User;
import objectFactory.Client;
import businessLayer.BLServices;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import objectFactory.Services;
import objectFactory.Subscription;
import businessLayer.BLSubscription;
import objectFactory.Account;
import businessLayer.BLAccount;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Kriss
 */
public class CreateClientProfile extends javax.swing.JInternalFrame {

    /**
     * Creates new form CreateProfile
     */
    public CreateClientProfile() {
        super("Create Profile");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_firstName = new javax.swing.JTextField();
        txt_middleName = new javax.swing.JTextField();
        txt_lastName = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_blockCode = new javax.swing.JTextField();
        txt_streetName = new javax.swing.JTextField();
        txt_cityCode = new javax.swing.JTextField();
        txt_cityName = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_status = new javax.swing.JTextField();
        button_enter = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();
        txt_telephone = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setClosable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(569, 643));

        jLabel2.setText("First Name");

        jLabel3.setText("Middle Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Username");

        jLabel6.setText("Password");

        jLabel8.setText("Block Code");

        jLabel9.setText("Street Name");

        jLabel10.setText("City Code");

        jLabel11.setText("City Name");

        jLabel12.setText("Telephone");

        jLabel13.setText("Email");

        jLabel14.setText("Status");

        txt_cityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cityNameActionPerformed(evt);
            }
        });

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        button_enter.setText("Enter");
        button_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_enterActionPerformed(evt);
            }
        });

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane4.setViewportView(jScrollPane1);

        jLabel1.setText("Select service");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cityName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(txt_middleName)
                            .addComponent(txt_lastName)
                            .addComponent(txt_username)
                            .addComponent(txt_blockCode)
                            .addComponent(txt_streetName)
                            .addComponent(txt_cityCode)
                            .addComponent(txt_email)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button_enter))
                                .addGap(0, 150, Short.MAX_VALUE)))
                        .addGap(178, 178, 178))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane4)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_middleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_blockCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_streetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cityCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(button_enter)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void button_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_enterActionPerformed
        // TODO add your handling code here:
        char[] temp_pwd = txt_password.getPassword();
        String pwd = null;
        pwd = String.copyValueOf(temp_pwd);

        try {
            BLUser bluser = new BLUser();
            User user = new User();

            user.setUsername(txt_username.getText());
            user.setPassword(pwd);
            user.setUserType("client");

            bluser.setUser(user);

            /*Checking if username exists*/
            if (bluser.checkUsernameExist()) {
                JOptionPane.showMessageDialog(null, "Username: " + user.getUsername() + " already exists or it is blank! \nEnter another username.");

            } else {
                /*Insert user attributes' value*/
                bluser.insertUserProfile();

                /*Getting userId and putting the userId value and the remaining attributes of client entity*/
                Client client = new Client();
                user = new User();

                user = bluser.getUser();
                bluser.setUser(user);
                ResultSet rs = bluser.selectUserIdFromUsername(txt_username.getText());

                while (rs.next()) {
                    client.setUserId(rs.getInt("userId"));
                }

                client.setFirstName(txt_firstName.getText());
                client.setMiddleName(txt_middleName.getText());
                client.setLastName(txt_lastName.getText());
                client.setBlockCode(txt_blockCode.getText());
                client.setStreetName(txt_streetName.getText());
                client.setCityCode(txt_cityCode.getText());
                client.setCityName(txt_cityName.getText());
                client.setTelephone(txt_telephone.getText());
                client.setEmail(txt_email.getText());
                client.setStatus(txt_status.getText());

                bluser.setClient(client);
                bluser.insertClientProfile();

                JOptionPane.showMessageDialog(null, "New client as username: '" + user.getUsername() + "' is created.");

                /*Put Client id, name into Account table*/
                try {
                    BLAccount blaccount = new BLAccount();
                    Account account = new Account();

                    ResultSet rs1 = bluser.selectUserIdFromUsername(txt_username.getText());
                    user.setUsername(txt_username.getText());
                    bluser.setUser(user);

                    while (rs1.next())
                    {
                        account.setAccountHolderId(rs1.getInt("userId"));
                    }

                    account.setAccountHolderName(txt_firstName.getText() + " " + txt_middleName.getText() + " " + txt_lastName.getText());
                    account.setPaidDate("Not Paid");

                    blaccount.setAccount(account);
                    blaccount.insertAccount();

                }//end try
                catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.INFORMATION_MESSAGE);
                }//end catch

                /*Getting the service list*/
                viewServiceList();

                /*Select Service from the list*/
                selectService();

            }
        }//end try
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.INFORMATION_MESSAGE);
        }//end catch

    }//GEN-LAST:event_button_enterActionPerformed

    public void setServices(Services services) {
        this.services = services;
    }

    /*Selecting the service*/
    public void selectService() {
        /*Getting the value at selected row and subscribing the selected row*/
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());

                /*Getting the id value of selected row*/
                String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                int num_id = Integer.parseInt(id);

                /*Confirming to subscribe*/
                int option = JOptionPane.showConfirmDialog(rootPane, "Service Id as: " + jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString() + " is going to be subscribed.", null, 2);
                if (option != JOptionPane.OK_OPTION) {
                    CreateClientProfile ccp = new CreateClientProfile();
                    ccp.setVisible(false);

                }//end while
                else {
                    try {
                        blservices.selectServices(num_id);

                        BLSubscription blsubscription = new BLSubscription();
                        Subscription subscription = new Subscription();

                        /*Getting subscription name = service name from  the selected row*/
                        String subscriptionName = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
                        subscription.setSubscripName(subscriptionName);

                        subscription.setServiceId(num_id);

                        /*Getting client userid from the inserted username*/
                        BLUser bluser = new BLUser();
                        User user = new User();

                        ResultSet rs = bluser.selectUserIdFromUsername(txt_username.getText());
                        while (rs.next()) {
                            subscription.setClientId(rs.getInt("userId"));
                        }

                        /*Days remaining to calculate from the service duration mentioned*/
                        /*Expiry date showing*/
                        Calendar date3 = Calendar.getInstance();
                        date3.setTime(new Date());
                        Format f = new SimpleDateFormat("yyyy/MM/dd");
                        date3.add(Calendar.YEAR, 1);
                        subscription.setExpiryDate(f.format(date3.getTime()));

                        /*Due remaining to check from the account section*/
                        //BLAccount blaccount = new BLAccount();
                        //Account account = new Account();
                        //rs = bluser.selectUserIdFromUsername(txt_username.getText());
                        //while (rs.next()) {
                        //  account.setAccountHolderId(rs.getInt("userId"));
                        //}
                        subscription.setDuePaid("No");

                        blsubscription.setSubscription(subscription);

                        /*That particular service is added to the subscription of the client*/
                        blsubscription.insertSubscription();
                        setVisible(false);

                        JOptionPane.showMessageDialog(null, "Welcome user: '" + txt_username.getText() + "'. \nYou are subscribed to " + jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString() + ". \nPay your bill and get authentication for subscription.");

                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.INFORMATION_MESSAGE);
                    }

                }

            }
        });
    }

    /*Viewing the serviceList*/
    public void viewServiceList() {
        blservices = new BLServices();
        services = new Services();

        DefaultTableModel dtm = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };

        try {
            dtm.addColumn("Service Id");
            dtm.addColumn("Service Name");
            dtm.addColumn("Bandwidth");
            dtm.addColumn("Duration");
            dtm.addColumn("Price");
            dtm.addColumn("Installation Cost");
            dtm.addColumn("Sharing Ratio");
            dtm.addColumn("Remarks");

            blservices.setServices(this.services);
            ResultSet rs = blservices.selectAllServices();

            while (rs.next()) {
                Object objData[] = new Object[8];
                objData[0] = rs.getInt("serviceId");
                objData[1] = rs.getString("serviceName");
                objData[2] = rs.getString("bandwidth");
                objData[3] = rs.getInt("duration");
                objData[4] = rs.getInt("price");
                objData[5] = rs.getInt("installationCost");
                objData[6] = rs.getString("sharingRatio");
                objData[7] = rs.getString("serviceRemarks");

                dtm.addRow(objData);
            }
            this.jTable1.setModel(dtm);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.INFORMATION_MESSAGE);
        }
    }


    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_cityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cityNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_blockCode;
    private javax.swing.JTextField txt_cityCode;
    private javax.swing.JTextField txt_cityName;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_middleName;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_streetName;
    private javax.swing.JTextField txt_telephone;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    private businessLayer.BLUser bluser;
    private objectFactory.User user;
    private objectFactory.Client client;

    private businessLayer.BLServices blservices;
    private objectFactory.Services services;

    private businessLayer.BLSubscription blsubscription;
    private objectFactory.Subscription subscription;

    private businessLayer.BLAccount blaccount;
    private objectFactory.Account account;
}
