/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myApplication;

import businessLayer.BLFeedback;
import businessLayer.BLRequest;
import businessLayer.BLUser;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import objectFactory.Feedback;
import objectFactory.User;

/**
 *
 * @author Kriss
 */
public class GiveFeedback extends javax.swing.JInternalFrame {

    /**
     * Creates new form GiveFeedback
     */
    public GiveFeedback() {
        super("Give Feedback");
        initComponents();
    }

    /*To show date in Text box
     To show new Request Id in Text box*/
    public void giveFeedback() {

        /*To show date in Text box*/
        //DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
        txt_date.setText(new String(dateFormat.format(date)));

        /*To get date n time by Calendar class
         Calendar cal = Calendar.getInstance();
         Calendar cal1 = Calendar.getInstance();
         System.out.println(dateFormat.format(cal.getTime()));*/
        /*To add time
         Calendar date3 = Calendar.getInstance();  
         date3.setTime(new Date());  
         Format f1 = new SimpleDateFormat("dd-MMMM-yyyy");  
         Format f = new SimpleDateFormat("yyyy/MM/dd");  
         System.out.println(f1.format(date.getTime()));  
         System.out.println(f.format(date.getTime()));  
         date3.add(Calendar.YEAR,1);  
         System.out.println(f.format(date3.getTime()));*/
        /*To show new Request Id in Text box*/
        try {
            BLFeedback blfeedback = new BLFeedback();
            ResultSet rs = blfeedback.selectMaxFeedbackId();

            while (rs.next()) {
                txt_feedbackId.setText(new Integer((rs.getInt("max_id")) + 1).toString());
            }
        }//end try
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.INFORMATION_MESSAGE);
        }//end catch

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_description = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_feedbackId = new javax.swing.JTextField();
        btn_feedback = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(458, 384));

        txtArea_description.setColumns(20);
        txtArea_description.setRows(5);
        jScrollPane1.setViewportView(txtArea_description);

        jLabel4.setText("Description");

        jLabel5.setText("User name");

        txt_date.setEditable(false);
        txt_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dateActionPerformed(evt);
            }
        });

        jLabel1.setText("Date");

        jLabel2.setText("Feedback Id");

        txt_feedbackId.setEditable(false);
        txt_feedbackId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_feedbackIdActionPerformed(evt);
            }
        });

        btn_feedback.setText("Feedback");
        btn_feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_feedbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(txt_username)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_feedbackId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_feedbackId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addComponent(btn_feedback)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dateActionPerformed
        // TODO add your handling code here:

        //date();
    }//GEN-LAST:event_txt_dateActionPerformed

    private void txt_feedbackIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_feedbackIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_feedbackIdActionPerformed

    private void btn_feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_feedbackActionPerformed
        // TODO add your handling code here:
        try {
        } catch (Exception ex) {
        }
        try {
            BLFeedback blfeedback = new BLFeedback();
            Feedback feedback = new Feedback();

            feedback.setCurrentDate(txt_date.getText());
            feedback.setFeedbackRemarks(txtArea_description.getText());

            /*To get the Client Id from the Username*/
            /*Check if the given Username exists*/
            try {
                BLUser bluser = new BLUser();
                User user = new User();
                ResultSet rs = bluser.selectUserIdFromUsername(txt_username.getText());

                /*Check if the given Username exists*/
                try {
                    user.setUsername(txt_username.getText());
                    bluser.setUser(user);

                    if (bluser.checkUsernameExist()) {
                        /*To get the Client Id from the Username*/
                        while (rs.next()) {
                            feedback.setClientId(rs.getInt("userId"));
                        }

                        blfeedback.setFeedback(feedback);
                        blfeedback.insertFeedback();

                        JOptionPane.showMessageDialog(null, "Username as: '" + txt_username.getText() + "' gave a feedback.");
                        setVisible(false);
                    }// end if
                    else {
                        JOptionPane.showMessageDialog(rootPane, "Invalid username!");
                    }// end else        

                }// end try
                catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.INFORMATION_MESSAGE);
                }//end catch

            }//end try
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.INFORMATION_MESSAGE);
            }//end catch

            
        }//end try
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.INFORMATION_MESSAGE);
        }//end catch

    }//GEN-LAST:event_btn_feedbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_feedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea_description;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_feedbackId;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
    private objectFactory.Feedback feedback;
    private businessLayer.BLFeedback blfeedback;
}
