/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myApplication;

import objectFactory.User;
import businessLayer.BLUser;
import javax.swing.JOptionPane;
import businessLayer.BLServices;
import objectFactory.Rating;
import objectFactory.Services;
import objectFactory.Request;
import objectFactory.Response;
import businessLayer.BLRequestResponse;

/**
 *
 * @author Kriss
 */
public class OperatorDesktop extends javax.swing.JFrame {

    /**
     * Creates new form StaffDesktop
     */
    public OperatorDesktop() {
        super("Operator Desktop");
        initComponents();
        this.user = new User();
        this.services = new Services();
        this.rating = new Rating();
        this.request = new Request();
        this.response = new Response();
    }

    public void setUser(User usr) {
        this.user = usr;

    }

    public void setServices(Services services) {
        this.services = services;
    }

    public void setRating(Rating rating) {
        this.rating = rating;
    }

    public void setRequest(Request request) {
        this.request = request;
    }

    public void setResponse(Response response) {
        this.response = response;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        menu_logOut = new javax.swing.JMenuItem();
        menu_exit = new javax.swing.JMenuItem();
        menu_view = new javax.swing.JMenu();
        menu_viewClientProfile = new javax.swing.JMenuItem();
        menu_viewOfficeStaffProfile = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_viewServiceList = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menu_viewRequestResponse = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menu_viewPi_chart = new javax.swing.JMenuItem();
        menu_subscription = new javax.swing.JMenu();
        menu_newSubscription = new javax.swing.JMenuItem();
        menu_updateSubscription = new javax.swing.JMenuItem();
        menu_input_Data = new javax.swing.JMenu();
        menu_updateClientProfile = new javax.swing.JMenuItem();
        menu_deleteClientProfile = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menu_insertService = new javax.swing.JMenuItem();
        menu_updateService = new javax.swing.JMenuItem();
        menu_deleteService = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menu_createStaffProfile = new javax.swing.JMenuItem();
        menu_updateStaffProfile = new javax.swing.JMenuItem();
        menu_deleteStaffProfile = new javax.swing.JMenuItem();
        menu_request = new javax.swing.JMenu();
        menu_maintainence = new javax.swing.JMenuItem();
        menu_feedback = new javax.swing.JMenu();
        menu_giveFeedback = new javax.swing.JMenuItem();
        menu_rateSubscription = new javax.swing.JMenu();
        menu_rateSubscripiton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 700));

        menu_file.setMnemonic('f');
        menu_file.setText("File");

        menu_logOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menu_logOut.setText("Log out");
        menu_logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_logOutActionPerformed(evt);
            }
        });
        menu_file.add(menu_logOut);

        menu_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menu_exit.setMnemonic('x');
        menu_exit.setText("Exit");
        menu_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_exitActionPerformed(evt);
            }
        });
        menu_file.add(menu_exit);

        menuBar.add(menu_file);

        menu_view.setText("View");

        menu_viewClientProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_viewClientProfile.setText("Client Profile");
        menu_viewClientProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_viewClientProfileActionPerformed(evt);
            }
        });
        menu_view.add(menu_viewClientProfile);

        menu_viewOfficeStaffProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        menu_viewOfficeStaffProfile.setText("Office Staff Profile");
        menu_viewOfficeStaffProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_viewOfficeStaffProfileActionPerformed(evt);
            }
        });
        menu_view.add(menu_viewOfficeStaffProfile);
        menu_view.add(jSeparator1);

        menu_viewServiceList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menu_viewServiceList.setText("Service List");
        menu_viewServiceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_viewServiceListActionPerformed(evt);
            }
        });
        menu_view.add(menu_viewServiceList);
        menu_view.add(jSeparator4);

        menu_viewRequestResponse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menu_viewRequestResponse.setText("Request/Response");
        menu_viewRequestResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_viewRequestResponseActionPerformed(evt);
            }
        });
        menu_view.add(menu_viewRequestResponse);
        menu_view.add(jSeparator5);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Subscription");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_view.add(jMenuItem1);
        menu_view.add(jSeparator6);

        menu_viewPi_chart.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menu_viewPi_chart.setText("Rating");
        menu_viewPi_chart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_viewPi_chartActionPerformed(evt);
            }
        });
        menu_view.add(menu_viewPi_chart);

        menuBar.add(menu_view);

        menu_subscription.setText("Subscription");

        menu_newSubscription.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menu_newSubscription.setText("New");
        menu_newSubscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_newSubscriptionActionPerformed(evt);
            }
        });
        menu_subscription.add(menu_newSubscription);

        menu_updateSubscription.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menu_updateSubscription.setText("Update");
        menu_updateSubscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_updateSubscriptionActionPerformed(evt);
            }
        });
        menu_subscription.add(menu_updateSubscription);

        menuBar.add(menu_subscription);

        menu_input_Data.setBorder(null);
        menu_input_Data.setText("Data");

        menu_updateClientProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_updateClientProfile.setText("Update Client Profile");
        menu_updateClientProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_updateClientProfileActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_updateClientProfile);

        menu_deleteClientProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_deleteClientProfile.setText("Delete Client Profile");
        menu_deleteClientProfile.setBorder(null);
        menu_deleteClientProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_deleteClientProfileActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_deleteClientProfile);
        menu_input_Data.add(jSeparator2);

        menu_insertService.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_insertService.setText("Insert Service");
        menu_insertService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_insertServiceActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_insertService);

        menu_updateService.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_updateService.setText("Update Service");
        menu_updateService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_updateServiceActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_updateService);

        menu_deleteService.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_deleteService.setText("Delete Service");
        menu_deleteService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_deleteServiceActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_deleteService);
        menu_input_Data.add(jSeparator3);

        menu_createStaffProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_createStaffProfile.setText("Create Staff Profile");
        menu_createStaffProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_createStaffProfileActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_createStaffProfile);

        menu_updateStaffProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_updateStaffProfile.setText("Update Staff Profile");
        menu_updateStaffProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_updateStaffProfileActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_updateStaffProfile);

        menu_deleteStaffProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_deleteStaffProfile.setText("Delete Staff Profile");
        menu_deleteStaffProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_deleteStaffProfileActionPerformed(evt);
            }
        });
        menu_input_Data.add(menu_deleteStaffProfile);

        menuBar.add(menu_input_Data);

        menu_request.setText("Request");

        menu_maintainence.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        menu_maintainence.setText("Maintainence");
        menu_maintainence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_maintainenceActionPerformed(evt);
            }
        });
        menu_request.add(menu_maintainence);

        menuBar.add(menu_request);

        menu_feedback.setText("Feedback");

        menu_giveFeedback.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menu_giveFeedback.setText("Give Feedbak");
        menu_giveFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_giveFeedbackActionPerformed(evt);
            }
        });
        menu_feedback.add(menu_giveFeedback);

        menuBar.add(menu_feedback);

        menu_rateSubscription.setText("Rate");

        menu_rateSubscripiton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_rateSubscripiton.setText("Rate subscription");
        menu_rateSubscripiton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_rateSubscripitonActionPerformed(evt);
            }
        });
        menu_rateSubscription.add(menu_rateSubscripiton);

        menuBar.add(menu_rateSubscription);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_exitActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane, "The program is going to be exited.", null, 2);
        if (option == JOptionPane.OK_OPTION) {
            System.exit(0);
        } else {
            JOptionPane.getRootFrame();//setVisible(false);
        }
    }//GEN-LAST:event_menu_exitActionPerformed

    private void menu_createStaffProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_createStaffProfileActionPerformed
        CreateStaffProfile csp = new CreateStaffProfile();
        desktopPane.add(csp);
        csp.setVisible(true);
        
    }//GEN-LAST:event_menu_createStaffProfileActionPerformed

    private void menu_logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_logOutActionPerformed
        this.dispose();
        LoginForm1 lf = new LoginForm1();
        lf.setVisible(true);

    }//GEN-LAST:event_menu_logOutActionPerformed

    private void menu_viewPi_chartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_viewPi_chartActionPerformed
        ViewRating vpc = new ViewRating();
        vpc.setRating(rating);
        vpc.drawPi_chart();

    }//GEN-LAST:event_menu_viewPi_chartActionPerformed

    private void menu_viewClientProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_viewClientProfileActionPerformed
        ViewClientProfile vpd = new ViewClientProfile();
        desktopPane.add(vpd);
        vpd.setUser(user);
        vpd.setVisible(true);
        vpd.viewClientProfile();
        
    }//GEN-LAST:event_menu_viewClientProfileActionPerformed

    private void menu_viewServiceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_viewServiceListActionPerformed
        ViewServiceList vsl = new ViewServiceList();
        desktopPane.add(vsl);
        vsl.setServices(services);
        vsl.setVisible(true);
        vsl.viewServiceList();

    }//GEN-LAST:event_menu_viewServiceListActionPerformed

    private void menu_viewRequestResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_viewRequestResponseActionPerformed
        ViewRequestResponse vres = new ViewRequestResponse();
        desktopPane.add(vres);
        vres.setRequest(request);
        vres.setResponse(response);
        vres.setVisible(true);
        vres.viewRequestResponse();

    }//GEN-LAST:event_menu_viewRequestResponseActionPerformed

    private void menu_newSubscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_newSubscriptionActionPerformed
        CreateClientProfile ccp = new CreateClientProfile();
        desktopPane.add(ccp);
        ccp.setVisible(true);
        ccp.viewServiceList();
    }//GEN-LAST:event_menu_newSubscriptionActionPerformed

    private void menu_updateSubscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_updateSubscriptionActionPerformed
        UpdateSubscription us_sl = new UpdateSubscription();
        desktopPane.add(us_sl);
        us_sl.setVisible(true);
        us_sl.viewEmptyServiceList();

    }//GEN-LAST:event_menu_updateSubscriptionActionPerformed

    private void menu_updateClientProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_updateClientProfileActionPerformed
        UpdateClientProfile up = new UpdateClientProfile();
        desktopPane.add(up);
        up.setVisible(true);
        up.updateClientProfile();
    }//GEN-LAST:event_menu_updateClientProfileActionPerformed

    private void menu_deleteClientProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_deleteClientProfileActionPerformed
        DeleteClientProfile dcp = new DeleteClientProfile();
        desktopPane.add(dcp);
        dcp.setVisible(true);
        dcp.deleteClientProfile();
    }//GEN-LAST:event_menu_deleteClientProfileActionPerformed

    private void menu_insertServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_insertServiceActionPerformed
        InsertService is = new InsertService();
        desktopPane.add(is);
        is.setVisible(true);
    }//GEN-LAST:event_menu_insertServiceActionPerformed

    private void menu_updateServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_updateServiceActionPerformed
        UpdateService us_l = new UpdateService();
        desktopPane.add(us_l);
        us_l.setServices(services);
        us_l.setVisible(true);
        us_l.updateService_List();
    }//GEN-LAST:event_menu_updateServiceActionPerformed

    private void menu_viewOfficeStaffProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_viewOfficeStaffProfileActionPerformed
        ViewOfficeStaffProfile vosp = new ViewOfficeStaffProfile();
        desktopPane.add(vosp);
        vosp.setUser(user);
        vosp.setVisible(true);
        vosp.viewOfficeStaffProfile();

    }//GEN-LAST:event_menu_viewOfficeStaffProfileActionPerformed

    private void menu_deleteServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_deleteServiceActionPerformed
        DeleteService ds = new DeleteService();
        desktopPane.add(ds);
        ds.setServices(services);
        ds.setVisible(true);
        ds.deleteService();

    }//GEN-LAST:event_menu_deleteServiceActionPerformed

    private void menu_rateSubscripitonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_rateSubscripitonActionPerformed
        RateSubscription rsub = new RateSubscription();
        desktopPane.add(rsub);
        rsub.setVisible(true);

    }//GEN-LAST:event_menu_rateSubscripitonActionPerformed

    private void menu_updateStaffProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_updateStaffProfileActionPerformed
        UpdateStaffProfile usp = new UpdateStaffProfile();
        desktopPane.add(usp);
        usp.setVisible(true);
        usp.updateOfficeStaffProfile();

    }//GEN-LAST:event_menu_updateStaffProfileActionPerformed

    private void menu_deleteStaffProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_deleteStaffProfileActionPerformed
        DeleteStaffProfile dsp = new DeleteStaffProfile();
        desktopPane.add(dsp);
        dsp.setVisible(true);
        dsp.deleteOfficeStaffProfile();
        
    }//GEN-LAST:event_menu_deleteStaffProfileActionPerformed

    private void menu_maintainenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_maintainenceActionPerformed
        RequestMaintainence rm = new RequestMaintainence();
        desktopPane.add(rm);
        rm.setVisible(true);
        rm.requestMaintainence();
    }//GEN-LAST:event_menu_maintainenceActionPerformed

    private void menu_giveFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_giveFeedbackActionPerformed
        GiveFeedback rm = new GiveFeedback();
        desktopPane.add(rm);
        rm.setVisible(true);
        rm.giveFeedback();
        
    }//GEN-LAST:event_menu_giveFeedbackActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ViewSubscription vs = new ViewSubscription();
        desktopPane.add(vs);
        vs.setVisible(true);
        vs.viewEmptyServiceList();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperatorDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperatorDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperatorDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperatorDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperatorDesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menu_createStaffProfile;
    private javax.swing.JMenuItem menu_deleteClientProfile;
    private javax.swing.JMenuItem menu_deleteService;
    private javax.swing.JMenuItem menu_deleteStaffProfile;
    private javax.swing.JMenuItem menu_exit;
    private javax.swing.JMenu menu_feedback;
    private javax.swing.JMenu menu_file;
    private javax.swing.JMenuItem menu_giveFeedback;
    private javax.swing.JMenu menu_input_Data;
    private javax.swing.JMenuItem menu_insertService;
    private javax.swing.JMenuItem menu_logOut;
    private javax.swing.JMenuItem menu_maintainence;
    private javax.swing.JMenuItem menu_newSubscription;
    private javax.swing.JMenuItem menu_rateSubscripiton;
    private javax.swing.JMenu menu_rateSubscription;
    private javax.swing.JMenu menu_request;
    private javax.swing.JMenu menu_subscription;
    private javax.swing.JMenuItem menu_updateClientProfile;
    private javax.swing.JMenuItem menu_updateService;
    private javax.swing.JMenuItem menu_updateStaffProfile;
    private javax.swing.JMenuItem menu_updateSubscription;
    private javax.swing.JMenu menu_view;
    private javax.swing.JMenuItem menu_viewClientProfile;
    private javax.swing.JMenuItem menu_viewOfficeStaffProfile;
    private javax.swing.JMenuItem menu_viewPi_chart;
    private javax.swing.JMenuItem menu_viewRequestResponse;
    private javax.swing.JMenuItem menu_viewServiceList;
    // End of variables declaration//GEN-END:variables

    private objectFactory.User user;
    private businessLayer.BLUser blUser;

    private objectFactory.Services services;
    private businessLayer.BLServices blservices;

    private objectFactory.Rating rating;
    private businessLayer.BLRating blrating;

    private objectFactory.Request request;
    private objectFactory.Response response;
    private businessLayer.BLRequestResponse blRequestResponse;
}
