/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package myApplication;

import javax.swing.ButtonGroup;
import businessLayer.BLRating;
import javax.swing.JOptionPane;
import objectFactory.Rating;
import businessLayer.BLUser;
import objectFactory.User;


/**
 *
 * @author Kriss
 */
public class RateSubscription extends javax.swing.JInternalFrame {

    /**
     * Creates new form RateSubscription
     */
    public RateSubscription() {
        super("Rate Subscription");
        initComponents();
        groupRadios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        radio_excellent = new javax.swing.JRadioButton();
        radio_good = new javax.swing.JRadioButton();
        radio_satisfactory = new javax.swing.JRadioButton();
        radio_notBad = new javax.swing.JRadioButton();
        radio_bad = new javax.swing.JRadioButton();
        btn_ok = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setClosable(true);

        jLabel1.setText("Please rate the quality of the service being used.");

        radio_excellent.setText("Excellent");
        radio_excellent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_excellentActionPerformed(evt);
            }
        });

        radio_good.setText("Good");

        radio_satisfactory.setText("Satisfactory");

        radio_notBad.setText("Not Bad");

        radio_bad.setText("Bad");

        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_good)
                            .addComponent(radio_excellent)
                            .addComponent(radio_satisfactory)
                            .addComponent(radio_notBad)
                            .addComponent(radio_bad))))
                .addGap(0, 94, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(radio_excellent)
                .addGap(18, 18, 18)
                .addComponent(radio_good)
                .addGap(18, 18, 18)
                .addComponent(radio_satisfactory)
                .addGap(18, 18, 18)
                .addComponent(radio_notBad)
                .addGap(18, 18, 18)
                .addComponent(radio_bad)
                .addGap(18, 18, 18)
                .addComponent(btn_ok)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_excellentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_excellentActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_radio_excellentActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // TODO add your handling code here:
        try {
            BLRating blrating = new BLRating();
            Rating  rating = new Rating();
            
            if(radio_excellent.isSelected()) {
                rating.setRatingName("Excellent");
                
            }
            
            else if(radio_good.isSelected()) {
                rating.setRatingName("Good");
            }
            
            else if(radio_satisfactory.isSelected()) {
                rating.setRatingName("Satisfactory");
            }
            
            else if(radio_notBad.isSelected()) {
                rating.setRatingName("Not bad");
            }
            
            else if(radio_bad.isSelected()) {
                rating.setRatingName("Bad");
            }
            
            blrating.setRating(rating);
            blrating.insertRating();
            
            JOptionPane.showMessageDialog(null,"You rated as " + rating.getRatingName() + ".");
            setVisible(false);
            
        }//end try
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.INFORMATION_MESSAGE);
        }//end catch
    }//GEN-LAST:event_btn_okActionPerformed

    public void groupRadios() {
        ButtonGroup rating_group = new ButtonGroup();
        
        rating_group.add(radio_excellent);
        rating_group.add(radio_good);
        rating_group.add(radio_satisfactory);
        rating_group.add(radio_notBad);
        rating_group.add(radio_bad);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton radio_bad;
    private javax.swing.JRadioButton radio_excellent;
    private javax.swing.JRadioButton radio_good;
    private javax.swing.JRadioButton radio_notBad;
    private javax.swing.JRadioButton radio_satisfactory;
    // End of variables declaration//GEN-END:variables
    private businessLayer.BLRating blrating;
    private objectFactory.Rating rating;
}
