/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package myApplication;

import objectFactory.User;
import businessLayer.BLUser;
import objectFactory.Request;
import businessLayer.BLRequest;
import java.sql.ResultSet;

import java.text.DateFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Krishna
 */
public class RequestMaintainence extends javax.swing.JInternalFrame {

    /**
     * Creates new form RequestMaintainence
     */
    public RequestMaintainence() {
        super("Request Maintainence");
        initComponents();
    }

    /*To show date in Text box
      To show new Request Id in Text box*/
    public void requestMaintainence(){
        
        /*To show date in Text box*/
        //DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
        txt_date.setText(new String(dateFormat.format(date)));
        
        /*To get date n time by Calendar class
        Calendar cal = Calendar.getInstance();
        Calendar cal1 = Calendar.getInstance();
	System.out.println(dateFormat.format(cal.getTime()));*/
        
        /*To add time
        Calendar date3 = Calendar.getInstance();  
        date3.setTime(new Date());  
        Format f1 = new SimpleDateFormat("dd-MMMM-yyyy");  
        Format f = new SimpleDateFormat("yyyy/MM/dd");  
        System.out.println(f1.format(date.getTime()));  
        System.out.println(f.format(date.getTime()));  
        date3.add(Calendar.YEAR,1);  
        System.out.println(f.format(date3.getTime()));*/  
        
        
        /*To show new Request Id in Text box*/
        try {
            BLRequest blrequest = new BLRequest();
            ResultSet rs = blrequest.selectMaxRequestId();
            
            while(rs.next()){
                txt_requestId.setText(new Integer((rs.getInt("max_id"))+1).toString());
            }
        }//end try
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.INFORMATION_MESSAGE);
        }//end catch

        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_subject = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_description = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        btn_request = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_requestId = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 204, 255));
        setClosable(true);

        jLabel1.setText("Date");

        txt_date.setEditable(false);
        txt_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dateActionPerformed(evt);
            }
        });

        jLabel3.setText("Subject");

        jLabel4.setText("Description");

        txtArea_description.setColumns(20);
        txtArea_description.setRows(5);
        jScrollPane1.setViewportView(txtArea_description);

        jLabel5.setText("User name");

        btn_request.setText("Request");
        btn_request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_requestActionPerformed(evt);
            }
        });
        btn_request.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_requestKeyPressed(evt);
            }
        });

        jLabel2.setText("Request Id");

        txt_requestId.setEditable(false);
        txt_requestId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_requestIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_subject, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(txt_username)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_requestId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_request)
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_requestId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btn_request)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dateActionPerformed
        // TODO add your handling code here:
        
        //date();
    }//GEN-LAST:event_txt_dateActionPerformed

    private void txt_requestIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_requestIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_requestIdActionPerformed

    private void btn_requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_requestActionPerformed
        // TODO add your handling code here:
        try {}
        catch (Exception ex) {}
        try {
            BLRequest blrequest = new BLRequest();
            Request request = new Request();
                    
            request.setCurrentDate(txt_date.getText());
            request.setRequestId(Integer.parseInt(txt_requestId.getText()));
            request.setRequestSubject(txt_subject.getText());
            request.setRequestDescrip(txtArea_description.getText());
        
            /*To get the Client Id from the Username*/
            /*Check if the given Username exists*/
            try {
                BLUser bluser = new BLUser();
                User user = new User();
                ResultSet rs = bluser.selectUserIdFromUsername(txt_username.getText());
                
                /*Check if the given Username exists*/
                try {
                    user.setUsername(txt_username.getText());
                    bluser.setUser(user);
            
                    if(bluser.checkUsernameExist()) {
                        /*To get the Client Id from the Username*/
                        while(rs.next()){
                            request.setClientId(rs.getInt("userId"));
                        }
                
                        blrequest.setRequest(request);
                        blrequest.insertRequest();
                
                        JOptionPane.showMessageDialog(null, "Request Name as '" + request.getRequestSubject() + "' sent as a request.");
                        setVisible(false);
                    }// end if
            
                    else {
                        JOptionPane.showMessageDialog(rootPane, "Invalid username!");
                    }// end else        
                
                }// end try
                catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.INFORMATION_MESSAGE);
                }//end catch
                
                
            }//end try
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.INFORMATION_MESSAGE);
            }//end catch
        
        }//end try
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.INFORMATION_MESSAGE);
        }//end catch
        
    }//GEN-LAST:event_btn_requestActionPerformed

    private void btn_requestKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_requestKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_requestKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_request;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea_description;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_requestId;
    private javax.swing.JTextField txt_subject;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
    //private businessLayer.BLRequest blrequest;
    //private objectFactory.Request request;
}
