/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myApplication;

import businessLayer.BLRequestResponse;
import businessLayer.BLServices;
import businessLayer.BLSubscription;
import businessLayer.BLUser;
import java.sql.ResultSet;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import objectFactory.Services;
import objectFactory.Subscription;
import objectFactory.User;

/**
 *
 * @author Kriss
 */
public class ViewSubscription extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewServiceList1
     */
    public ViewSubscription() {
        super("View Subscription");
        initComponents();
        blsubscription = new BLSubscription();
        subscription = new Subscription();

    }

    public void setSubscription(Subscription subscription) {
        this.subscription = subscription;
    }

    public void viewEmptyServiceList() {
        DefaultTableModel dtm = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };

        try {
            dtm.addColumn("Subscription Id");
            dtm.addColumn("Subscription Name");
            dtm.addColumn("Service Id");
            dtm.addColumn("Expiry Date");
            //dtm.addColumn("Due Paid");
            
            blsubscription.setSubscription(this.subscription);
            ResultSet rs = blsubscription.selectAllSubscription();

            Object objData[] = new Object[4];
            for (int i = 0; i <= 3; i++) {
                objData[i] = 0;
            }

            dtm.addRow(objData);
            this.jTable1.setModel(dtm);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /*Check if the given Username exists and get User Id from username*/
    public void checkUsernameExist() {

        try {
            BLUser bluser = new BLUser();
            User user = new User();

            ResultSet rs = bluser.selectUserIdFromUsername(txt_username.getText());

            user.setUsername(txt_username.getText());
            bluser.setUser(user);

            if (bluser.checkUsernameExist()) {
                /*To get the Client Id from the Username*/
                while (rs.next()) {
                    subscription.setClientId(rs.getInt("userId"));
                }
                viewServiceList();
            }// end if
            else {
                JOptionPane.showMessageDialog(rootPane, "Invalid username!");
            }// end else        

        }// end try
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.INFORMATION_MESSAGE);
        }//end catch
    }

    /*Then populate the service list table*/
    public void viewServiceList() {
        DefaultTableModel dtm = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };

        try {
            dtm.addColumn("Subscription Id");
            dtm.addColumn("Subscription Name");
            dtm.addColumn("Service Id");
            dtm.addColumn("Expiry Date");
            //dtm.addColumn("Due Paid");
            
            blsubscription.setSubscription(this.subscription);
            ResultSet rs = blsubscription.selectUserSubscription();

            while (rs.next()) {
                Object objData[] = new Object[4];
                objData[0] = rs.getInt("subscripId");
                objData[1] = rs.getString("subscripName");
                objData[2] = rs.getInt("serviceId");
                objData[3] = rs.getString("expiryDate");
                //objData[4] = rs.getString("duePaid");
                
                dtm.addRow(objData);
            }
            this.jTable1.setModel(dtm);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_enter2 = new javax.swing.JButton();
        txt_username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setClosable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(1265, 643));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel1.setText("Client Username");

        btn_enter2.setText("Enter");
        btn_enter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enter2ActionPerformed(evt);
            }
        });
        btn_enter2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_enter2KeyPressed(evt);
            }
        });

        jLabel2.setText("Subscription ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_enter2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_enter2))
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enter2ActionPerformed
        /*First check if username exist*/
        checkUsernameExist();

        //viewServiceList();
    }//GEN-LAST:event_btn_enter2ActionPerformed

    private void btn_enter2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_enter2KeyPressed
        /*First check if username exist*/
        checkUsernameExist();

        //viewServiceList();
    }//GEN-LAST:event_btn_enter2KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enter2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
    private objectFactory.Subscription subscription;
    private businessLayer.BLSubscription blsubscription;
}
